### ISSUE TITLE
Install Matlab module after installing pre built binaries

### ISSUE THREAD

**Issue by ricardojdferreira** [Itseez/opencv_contrib#390]
When building the opencv together with the matlab module, there is an error in the cmake config:

Trying to generate Matlab code
Traceback (most recent call last):
  File "C:/Users/Ricardo Ferreira/Desktop/opencv-master/modules/matlab/generator/gen_matlab.py", line 204, in <module>
    mwg.gen(args.moduleroot, args.modules, args.extra, args.outdir)
  File "C:/Users/Ricardo Ferreira/Desktop/opencv-master/modules/matlab/generator/gen_matlab.py", line 32, in gen
    import rst_parser
ImportError: No module named rst_parser

where can I find that python module?

**Comment by berak** [comment]
opencv switched to doxygen a while ago, and thus all rst related things got removed.

could you try [this attempt at fixing it](https://github.com/berak/opencv_contrib/tree/fix_matlab_rst) ?

**Comment by mshabunin** [comment]
Duplicate issue #167 has been fixed
